# Site settings
title: 2015 UW Python Seminar and Bootcamp
email: jakevdp -- AT -- uw.edu
description: "Information on the 2015 UW Python bootcamp and seminar, sponsored by UW eScience"
baseurl: "http://uwescience.github.io/python-seminar-2015/"
url: "http://uwescience.github.io/python-seminar-2015/"
twitter_username: uwescience
github_username:  uwescience


# Build settings
markdown: kramdown
